-- Consistency & Routines Implementation
-- This migration adds tables for tracking daily routines, consistency logs (the Diary), and AI-generated timetables.

-- 1. Routines Table (Definition of periodic tasks)
CREATE TABLE IF NOT EXISTS routines (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    start_time TIME NOT NULL, -- e.g. 08:00:00
    days_of_week INTEGER[] DEFAULT '{1,2,3,4,5,6,7}', -- 1=Mon, 7=Sun
    deadline DATE, -- End date for the entire routine commitment
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Routine Logs (The Diary / Mindmap data / Analytics)
CREATE TABLE IF NOT EXISTS routine_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    routine_id UUID REFERENCES routines(id) ON DELETE CASCADE,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    log_date DATE NOT NULL DEFAULT CURRENT_DATE,
    time_spent_minutes INTEGER DEFAULT 0,
    status TEXT CHECK (status IN ('done', 'ignored', 'postponed', 'pending')) DEFAULT 'pending',
    learning_notes TEXT,
    mindmap_data JSONB, -- For the "mindmap" feature storage
    actual_response_time TIMESTAMPTZ,
    postponed_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(routine_id, log_date)
);

-- 3. AI Timetables (Weekly AI-generated plans)
CREATE TABLE IF NOT EXISTS ai_timetables (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    week_start DATE NOT NULL,
    schedule_data JSONB NOT NULL, -- Full weekly structure generated by AI
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, week_start)
);

-- Enable RLS
ALTER TABLE routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE routine_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_timetables ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their own routines') THEN
        CREATE POLICY "Users can manage their own routines" ON routines FOR ALL USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their own routine logs') THEN
        CREATE POLICY "Users can manage their own routine logs" ON routine_logs FOR ALL USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their own AI timetables') THEN
        CREATE POLICY "Users can manage their own AI timetables" ON ai_timetables FOR ALL USING (auth.uid() = user_id);
    END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_routines_user_id ON routines(user_id);
CREATE INDEX IF NOT EXISTS idx_routine_logs_date ON routine_logs(log_date);
CREATE INDEX IF NOT EXISTS idx_ai_timetables_user_week ON ai_timetables(user_id, week_start);
