import * as db from './database';
import { routineService } from './routineService';
import { supabase } from '../lib/supabase';

export const EXEC_STATUS = {
    SUCCESS: 'success',
    FAILED: 'failed',
    UNAUTHORIZED: 'unauthorized'
};

/**
 * Service to execute actions generated by ZEN AI.
 * Validates permissions before execution.
 */
export const zenService = {
    /**
     * Executes a batch of actions from the ZEN response.
     * @param {Array} actions - Array of actions to execute e.g. [{ type: 'CREATE_TASK', payload: {...} }]
     * @param {Object} currentUser - Current authenticated user profile
     * @returns {Promise<Array>} Results of each execution
     */
    async executeActions(actions, currentUser) {
        if (!actions || !Array.isArray(actions)) return [];
        const results = [];

        for (const action of actions) {
            try {
                const isAdminOnly = [
                    'CREATE_TASK', 'UPDATE_TASK', 'DELETE_TASK',
                    'CREATE_QUIZ', 'UPDATE_QUIZ', 'DELETE_QUIZ',
                    'UPDATE_ROLE', 'EVALUATE_SUBMISSION', 'CREATE_INVITE',
                    'ADD_KB_MATERIAL', 'CREATE_ANNOUNCEMENT', 'SEND_PUSH',
                    'REMOVE_MEMBER', 'DELETE_KB_MATERIAL', 'UPDATE_KB_MATERIAL'
                ].includes(action.type);

                // Permission check
                if (isAdminOnly && currentUser?.role !== 'admin') {
                    results.push({
                        action: action.type,
                        status: EXEC_STATUS.UNAUTHORIZED,
                        message: `Action ${action.type} requires admin privileges.`
                    });
                    continue;
                }

                let resData = null;
                switch (action.type) {
                    // --- ROUTINE ACTIONS (Available to all users) ---
                    case 'CREATE_ROUTINE':
                        resData = await routineService.createRoutine(action.payload);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'UPDATE_ROUTINE':
                        resData = await routineService.updateRoutine(action.payload.id, action.payload.updates);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'DELETE_ROUTINE':
                        await routineService.deleteRoutine(action.payload.id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, id: action.payload.id });
                        break;
                    case 'LOG_ROUTINE':
                        resData = await routineService.logRoutineProgress(action.payload.routine_id, action.payload);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'CLEAR_ALL_LOGS':
                        await routineService.clearAllLogs();
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS });
                        break;
                    case 'CLEAR_ROUTINE_LOGS':
                        await routineService.clearLogsForRoutine(action.payload.routine_id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS });
                        break;
                    case 'BULK_SCHEDULE':
                        resData = await routineService.replaceAllRoutines(action.payload.routines);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;

                    // --- STUDY NOTES ACTIONS (Available to all users) ---
                    case 'ADD_STUDY_NOTE':
                        resData = await db.addStudyNote(action.payload);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'UPDATE_STUDY_NOTE':
                        resData = await db.updateStudyNote(action.payload.id, action.payload.updates);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'DELETE_STUDY_NOTE':
                        await db.deleteStudyNote(action.payload.id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS });
                        break;

                    // --- NOTIFICATION ACTIONS ---
                    case 'MARK_NOTIFICATIONS_READ':
                        await db.markAllNotificationsRead(currentUser.id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS });
                        break;

                    // --- NAVIGATION ACTION (Client UI only) ---
                    case 'NAVIGATE':
                        window.dispatchEvent(new CustomEvent('navigate-to-url', { detail: { url: action.payload.url } }));
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: action.payload.url });
                        break;

                    // --- TASK ACTIONS (Admin Only) ---
                    case 'CREATE_TASK':
                        resData = await db.createTask(action.payload);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'UPDATE_TASK':
                        resData = await db.updateTask(action.payload.id, action.payload.updates);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'DELETE_TASK':
                        await db.deleteTask(action.payload.id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, id: action.payload.id });
                        break;

                    // --- QUIZ ACTIONS (Admin Only) ---
                    case 'CREATE_QUIZ':
                        resData = await db.createQuiz(action.payload);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'UPDATE_QUIZ':
                        resData = await db.updateQuiz(action.payload.id, action.payload.updates);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;
                    case 'DELETE_QUIZ':
                        await db.deleteQuiz(action.payload.id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, id: action.payload.id });
                        break;

                    // --- ROLE ACTIONS (Admin Only) ---
                    case 'UPDATE_ROLE':
                        resData = await db.updateProfile(action.payload.id, { role: action.payload.role });
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;

                    // --- EVALUATION ACTIONS (Admin Only) ---
                    case 'EVALUATE_SUBMISSION':
                        resData = await db.updateSubmission(action.payload.id, action.payload.updates);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;

                    // --- INVITE CODE ACTIONS (Admin Only) ---
                    case 'CREATE_INVITE':
                        resData = await db.createInviteCode(action.payload.code, action.payload.classroom_id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;

                    // --- ANNOUNCEMENT ACTIONS (Admin Only) ---
                    case 'CREATE_ANNOUNCEMENT':
                        resData = await db.createAnnouncement(action.payload);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;

                    // --- BULK PUSH PROTOCOL (Admin Only) ---
                    case 'SEND_PUSH':
                        await db.sendPush(action.payload);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS });
                        break;

                    // --- CLASSROOM MANAGEMENT ACTIONS (Admin Only) ---
                    case 'REMOVE_MEMBER':
                        await db.removeMemberFromClassroom(action.payload.classroom_id, action.payload.user_id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS });
                        break;

                    // --- KNOWLEDGE BASE ACTIONS (Admin Only) ---
                    case 'ADD_KB_MATERIAL': {
                        const { data, error } = await supabase
                            .from('knowledge_base')
                            .insert([action.payload])
                            .select()
                            .single();
                        if (error) throw error;
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data });
                        break;
                    }
                    case 'DELETE_KB_MATERIAL':
                        await db.deleteKnowledgeSnippet(action.payload.id);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS });
                        break;
                    case 'UPDATE_KB_MATERIAL':
                        resData = await db.updateKnowledgeSnippet(action.payload.id, action.payload.updates);
                        results.push({ action: action.type, status: EXEC_STATUS.SUCCESS, data: resData });
                        break;

                    default:
                        results.push({
                            action: action.type,
                            status: EXEC_STATUS.FAILED,
                            message: `Unknown action type: ${action.type}`
                        });
                }
            } catch (err) {
                console.error(`[ZenService] Action ${action.type} failed:`, err);
                results.push({
                    action: action.type,
                    status: EXEC_STATUS.FAILED,
                    message: err.message || 'Execution error'
                });
            }
        }

        return results;
    }
};
